/*
 * Application Module — Spring Boot WAR/JAR executable entry point
 */

plugins {
    id 'org.springframework.boot'
}

bootJar { enabled = true }
jar { enabled = false }

dependencies {
    implementation project(':shared-kernel')
    implementation project(':core-module')
    implementation 'org.springframework.boot:spring-boot-starter-web'
}
